name: ACH2026
author: ACH
url: https://ach2026.ach.org

# Section display settings
# section will display if true, else not visible
about: true 
program: false
speakers: false
partners: false
faq: false 